name: Bastian Greshake Tzovaras
bio: 'Generally, things are better if you put <i>open*</i> in front of them.'
photo_bio: 'Photographer in the streets, avid reader in the sheets.'
picture: 'assets/images/profile.jpg'

url: https://tzovar.as
#url: https://gedankenstuecke.github.io
#url: localhost:3000
# your url: http://USERNAME.github.io
permalink: /:title/

title: 'Bastian Greshake Tzovaras'
tagline: 'Research on opening up citizen science'

description: 'Bastian Greshake Tzovaras is a researcher with a background in biology and citizen science and an open science activist. He works as a senior researcher at The Alan Turing Institute. In 2011, he founded openSNP. He was awarded a PhD in Bioinformatics in 2018. In 2017 he joined the Open Humans Foundation as the Director of Research.'

markdown: kramdown
highlighter: rouge

#analytics: 'UA-74621325-1'
#disqus: mydisqus
facebook: bastian.greshake
twitter: gedankenstuecke
mastodon: https://scholar.social/@gedankenstuecke
bookwyrm: https://bookwyrm.social/user/gedankenstuecke
kofi: https://ko-fi.com/gedankenstuecke/shop
instagram: gedankenstuecke
#linkedin: mylinkedin
#youtube: myyoutube
#spotify: myspotify
flickr: gedankenstuecke
github: gedankenstuecke
keybase: gedankenstuecke
scholar: xmtDOnQAAAAJ
orcid: 0000-0002-9925-9623
email: bgreshake@gmail.com

exclude: [README.md, Gemfile, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
#paginate: 10
#paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

photography: true

# if you don't need about or blog, comment them out below
about: true
blog: true

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-last-modified-at

jekyll-mentions:
    base_url: https://github.com

feed:
    categories:
        - blog
    posts_limit: 40

author:
    name: Bastian Greshake Tzovaras
    url: https://tzovar.as
    image: assets/images/profile.jpg
    uri: https://orcid.org/0000-0002-9925-9623


logo: assets/images/profile.jpg

social:
    name: Bastian Greshake Tzovaras
    links:
        - https://scholar.social/@gedankenstuecke
        - https://www.github.com/gedankenstuecke
        - https://flickr.com/photos/gedankenstuecke
        - https://www.instagram.com/gedankenstuecke/
        - https://ko-fi.com/gedankenstuecke/
        - https://orcid.org/0000-0002-9925-9623
        - https://scholar.google.de/citations?user=xmtDOnQAAAAJ

